# sampleData = {
#     'HOST_URL': '10.170.137.115',
#     'DBTR_PORT': '18947',
#     'DBTRAGT': 'BANKDMY7',
#     'DBTR_NM': "PT. Bank Dummy 7",
#     'DBTR_ORGID': 'BANKDMY7_MERCH_100',
#     'DBTR_PRVTID': 'PT. Bunyamin',
#     'DBTRACCT_VALUE': '12345677789',
#     'DBTRACCT_TYPE': 'CACC',
#     'DBTRACCT_NAME': 'Dummy Account 7',
#     'DBTRACCT_PRXY_TYPE': '02',
#     'DBTRACCT_PRXY_ID': 'BANKDMY7.001@PTAP.COM',
#     'CDTR_PORT': '18948',
#     'CDTRAGT': 'BANKDMY8',
#     'CDTR_NM': 'PT. Bank Dummy 8',
#     'CDTR_ORGID': 'BANKDMY8_MERCH_100',
#     'CDTR_PRVTID': 'PT. Pypoh',
#     'CDTRACCT_VALUE': '12345678889',
#     'CDTRACCT_TYPE': 'CACC',
#     'CDTRACCT_NAME': 'Dummy Account 8',
#     'CDTRACCT_PRXY_TYPE': '02',
#     'CDTRACCT_PRXY_ID': 'BANKDMY8.001@PTAP.COM',
# }

sampleData = {
    'HOST_URL': '10.170.135.196',
    'DBTR_PORT': '18947',
    'DBTRAGT': 'BANKDMY7',
    'DBTR_NM': "PT. Bank Dummy 7",
    'DBTR_ORGID': 'BANKDMY7_MERCH_100',
    'DBTR_PRVTID': 'PT. Bunyamin',
    'DBTRACCT_VALUE': '12345677789',
    'DBTRACCT_TYPE': 'CACC',
    'DBTRACCT_NAME': 'Dummy Account 7',
    'DBTRACCT_PRXY_TYPE': '02',
    'DBTRACCT_PRXY_ID': 'BANKDMY7.001@PTAP.COM',
    'CDTR_PORT': '18948',
    'CDTRAGT': 'BANKDMY8',
    'CDTR_NM': 'PT. Bank Dummy 8',
    'CDTR_ORGID': 'BANKDMY8_MERCH_100',
    'CDTR_PRVTID': 'PT. Pypoh',
    'CDTRACCT_VALUE': '12345678889',
    'CDTRACCT_TYPE': 'CACC',
    'CDTRACCT_NAME': 'Dummy Account 8',
    'CDTRACCT_PRXY_TYPE': '02',
    'CDTRACCT_PRXY_ID': 'BANKDMY8.001@PTAP.COM',
}

# sampleData = {
#     'HOST_URL': '10.170.137.115',
#     'DBTR_PORT': '18908',
#     'DBTRAGT': 'ATOSIDJ1',
#     'DBTR_NM': "TELKOM INDONESI 2aA",
#     'DBTR_ORGID': 'ATOSIDJ1_MERCH_100',
#     'DBTR_PRVTID': 'PT. Bunyamin',
#     'DBTRACCT_VALUE': '7479638521',
#     'DBTRACCT_TYPE': 'CACC',
#     'DBTRACCT_NAME': 'Telkom Indonesia 2a',
#     'DBTRACCT_PRXY_TYPE': '02',
#     'DBTRACCT_PRXY_ID': 'ATOSIDJ1.001@PTAP.COM',
#     'CDTR_PORT': '18907',
#     'CDTRAGT': 'ARTGIDJA',
#     'CDTR_NM': 'TELKOM INDONESI 1aA',
#     'CDTR_ORGID': 'ARTGIDJA_MERCH_100',
#     'CDTR_PRVTID': 'PT. Pypoh',
#     'CDTRACCT_VALUE': '7479638520',
#     'CDTRACCT_TYPE': 'CACC',
#     'CDTRACCT_NAME': 'Telkom Indonesia 1a',
#     'CDTRACCT_PRXY_TYPE': '02',
#     'CDTRACCT_PRXY_ID': 'ARTGIDJA.001@PTAP.COM',
# }

cards = [
    {'title': 'Account Enquiry', 'content': '/AccountEnquiry', 'input': 'N'},
    {'title': 'Credit Transfer', 'content': '/CreditTransfer/account', 'input': 'N'},
    # {'title': 'Credit Transfer Reversal',
    #     'content': '/CreditTransferReversal'},
    # {'title': 'Credit Transfer Proxy', 'content': '/CreditTransferProxy'},
    # {'title': 'Payment Status', 'content': '/PaymentStatus'},
    {'title': 'Request For Pay ByAccount',
     'content': '/RequestForPay/account', 'input': 'N'},
    # {'title': 'Request For Pay ByProxy', 'content': '/RequestForPayByProxy'},
    {'title': 'Request For Pay RejectByAccount',
     'content': '/RequestForPayRejectByAccount', 'input': 'Y'},
    # {'title': 'Request For Pay RejectByProxy',
    #  'content': '/RequestForPayRejectByProxy'},
    # {'title': 'Credit Transfer RFP', 'content': '/CreditTransferRFP'},
    # {'title': 'Mandate Regist By Credit',
    #     'content': '/MandateRegistByCredit'},
    # {'title': 'Mandate Regist By Debit', 'content': '/MandateRegistByDebit'},
    # {'title': 'Mandate Approval By Credit',
    #     'content': '/MandateApprovalByCredit'},
    # {'title': 'Mandate Approval By Debit',
    #     'content': '/MandateApprovalByDebit'},
    # {'title': 'Mandate Amend By Credit', 'content': '/MandateAmendByCredit'},
    # {'title': 'Mandate Amend By Debit', 'content': '/MandateAmendByDebit'},
    # {'title': 'Mandate Amend Approval By Credit',
    #     'content': '/MandateAmendApprovalByCredit'},
    # {'title': 'Mandate Amend Approval By Debit',
    #     'content': '/MandateAmendApprovalByDebit'},
    # {'title': 'Mandate Terminate By Credit',
    #     'content': '/MandateTerminateByCredit'},
    # {'title': 'Mandate Terminate By Debit',
    #     'content': '/MandateTerminateByDebit'},
    # {'title': 'Mandate Amend By Credit', 'content': '/MandateAmendByCredit'},
    # {'title': 'Mandate Enquiry', 'content': '/MandateEnquiry'},
    # {'title': 'Direct Debit', 'content': '/DirectDebit'},
    # {'title': 'Payment Status DD', 'content': '/PaymentStatusDD'},
]

# cards = [
#     {'title': 'Account Enquiry', 'content': '/AccountEnquiry'},
#     {'title': 'Credit Transfer', 'content': '/CreditTransfer'},
#     # {'title': 'Credit Transfer Reversal',
#     #     'content': '/CreditTransferReversal'},
#     # {'title': 'Credit Transfer Proxy', 'content': '/CreditTransferProxy'},
#     # {'title': 'Payment Status', 'content': '/PaymentStatus'},
#     # {'title': 'Proxy Registration', 'content': '/ProxyRegistration'},
#     # {'title': 'Proxy Porting', 'content': '/ProxyPorting'},
#     # {'title': 'Proxy Lookup', 'content': '/ProxyLookup'},
#     # {'title': 'Proxy Enquiry', 'content': '/ProxyEnquiry'},
#     # {'title': 'Proxy Deactivate', 'content': '/ProxyDeactivate'},
#     # {'title': 'Request For Pay ByAccount',
#     #     'content': '/RequestForPayByAccount'},
#     # {'title': 'Request For Pay ByProxy', 'content': '/RequestForPayByProxy'},
#     # {'title': 'Request For Pay RejectByAccount',
#     #     'content': '/RequestForPayRejectByAccount'},
#     # {'title': 'Request For Pay RejectByProxy',
#     #     'content': '/RequestForPayRejectByProxy'},
#     # {'title': 'Credit Transfer RFP', 'content': '/CreditTransferRFP'},
#     # {'title': 'Mandate Regist By Credit',
#     #     'content': '/MandateRegistByCredit'},
#     # {'title': 'Mandate Regist By Debit', 'content': '/MandateRegistByDebit'},
#     # {'title': 'Mandate Approval By Credit',
#     #     'content': '/MandateApprovalByCredit'},
#     # {'title': 'Mandate Approval By Debit',
#     #     'content': '/MandateApprovalByDebit'},
#     # {'title': 'Mandate Amend By Credit', 'content': '/MandateAmendByCredit'},
#     # {'title': 'Mandate Amend By Debit', 'content': '/MandateAmendByDebit'},
#     # {'title': 'Mandate Amend Approval By Credit',
#     #     'content': '/MandateAmendApprovalByCredit'},
#     # {'title': 'Mandate Amend Approval By Debit',
#     #     'content': '/MandateAmendApprovalByDebit'},
#     # {'title': 'Mandate Terminate By Credit',
#     #     'content': '/MandateTerminateByCredit'},
#     # {'title': 'Mandate Terminate By Debit',
#     #     'content': '/MandateTerminateByDebit'},
#     # {'title': 'Mandate Amend By Credit', 'content': '/MandateAmendByCredit'},
#     # {'title': 'Mandate Enquiry', 'content': '/MandateEnquiry'},
#     # {'title': 'Direct Debit', 'content': '/DirectDebit'},
#     # {'title': 'Payment Status DD', 'content': '/PaymentStatusDD'},
# ]
