# sampleData = {
#     'HOST_URL': '10.170.137.115',
#     'DBTR_PORT': '18947',
#     'DBTRAGT': 'BANKDMY7',
#     'DBTR_NM': "PT. Bank Dummy 7",
#     'DBTR_ORGID': 'BANKDMY7_MERCH_100',
#     'DBTR_PRVTID': 'PT. Bunyamin',
#     'DBTRACCT_VALUE': '12345677789',
#     'DBTRACCT_TYPE': 'CACC',
#     'DBTRACCT_NAME': 'Dummy Account 7',
#     'DBTRACCT_PRXY_TYPE': '02',
#     'DBTRACCT_PRXY_ID': 'BANKDMY7.001@PTAP.COM',
#     'CDTR_PORT': '18948',
#     'CDTRAGT': 'BANKDMY8',
#     'CDTR_NM': 'PT. Bank Dummy 8',
#     'CDTR_ORGID': 'BANKDMY8_MERCH_100',
#     'CDTR_PRVTID': 'PT. Pypoh',
#     'CDTRACCT_VALUE': '12345678889',
#     'CDTRACCT_TYPE': 'CACC',
#     'CDTRACCT_NAME': 'Dummy Account 8',
#     'CDTRACCT_PRXY_TYPE': '02',
#     'CDTRACCT_PRXY_ID': 'BANKDMY8.001@PTAP.COM',
# }

sampleData = {
    'HOST_URL': '10.170.137.115',
    'DBTR_PORT': '18908',
    'DBTRAGT': 'ATOSIDJ1',
    'DBTR_NM': "TELKOM INDONESI 2aA",
    'DBTR_ORGID': 'ATOSIDJ1_MERCH_100',
    'DBTR_PRVTID': 'PT. Bunyamin',
    'DBTRACCT_VALUE': '7479638521',
    'DBTRACCT_TYPE': 'CACC',
    'DBTRACCT_NAME': 'Telkom Indonesia 2a',
    'DBTRACCT_PRXY_TYPE': '02',
    'DBTRACCT_PRXY_ID': 'ATOSIDJ1.001@PTAP.COM',
    'CDTR_PORT': '18907',
    'CDTRAGT': 'ARTGIDJA',
    'CDTR_NM': 'TELKOM INDONESI 1aA',
    'CDTR_ORGID': 'ARTGIDJA_MERCH_100',
    'CDTR_PRVTID': 'PT. Pypoh',
    'CDTRACCT_VALUE': '7479638520',
    'CDTRACCT_TYPE': 'CACC',
    'CDTRACCT_NAME': 'Telkom Indonesia 1a',
    'CDTRACCT_PRXY_TYPE': '02',
    'CDTRACCT_PRXY_ID': 'ARTGIDJA.001@PTAP.COM',
}

cards = [
    {'title': 'Account Enquiry', 'content': '/AccountEnquiryOFI'},
    {'title': 'Credit Transfer', 'content': '/CreditTransferOFI'},
    # {'title': 'Credit Transfer Reversal',
    #     'content': '/CreditTransferReversalOFI'},
    {'title': 'Credit Transfer Proxy', 'content': '/CreditTransferProxyOFI'},
    # {'title': 'Payment Status', 'content': '/PaymentStatusOFI'},
    # {'title': 'Request For Pay ByAccount',
    #  'content': '/RequestForPayByAccountOFI'},
    # {'title': 'Request For Pay ByProxy', 'content': '/RequestForPayByProxyOFI'},
    # {'title': 'Request For Pay RejectByAccount',
    #  'content': '/RequestForPayRejectByAccountOFI'},
    # {'title': 'Request For Pay RejectByProxy',
    #  'content': '/RequestForPayRejectByProxyOFI'},
    # {'title': 'Credit Transfer RFP', 'content': '/CreditTransferRFPOFI'},
    # {'title': 'Mandate Regist By Credit',
    #     'content': '/MandateRegistByCreditOFI'},
    # {'title': 'Mandate Regist By Debit', 'content': '/MandateRegistByDebitOFI'},
    # {'title': 'Mandate Approval By Credit',
    #     'content': '/MandateApprovalByCreditOFI'},
    # {'title': 'Mandate Approval By Debit',
    #     'content': '/MandateApprovalByDebitOFI'},
    # {'title': 'Mandate Amend By Credit', 'content': '/MandateAmendByCreditOFI'},
    # {'title': 'Mandate Amend By Debit', 'content': '/MandateAmendByDebitOFI'},
    # {'title': 'Mandate Amend Approval By Credit',
    #     'content': '/MandateAmendApprovalByCreditOFI'},
    # {'title': 'Mandate Amend Approval By Debit',
    #     'content': '/MandateAmendApprovalByDebitOFI'},
    # {'title': 'Mandate Terminate By Credit',
    #     'content': '/MandateTerminateByCreditOFI'},
    # {'title': 'Mandate Terminate By Debit',
    #     'content': '/MandateTerminateByDebitOFI'},
    # {'title': 'Mandate Amend By Credit', 'content': '/MandateAmendByCreditOFI'},
    # {'title': 'Mandate Enquiry', 'content': '/MandateEnquiry'},
    # {'title': 'Direct Debit', 'content': '/DirectDebitOFI'},
    # {'title': 'Payment Status DD', 'content': '/PaymentStatusDDOFI'},
]

# cards = [
#     {'title': 'Account Enquiry', 'content': '/AccountEnquiryOFI'},
#     {'title': 'Credit Transfer', 'content': '/CreditTransferOFI'},
#     # {'title': 'Credit Transfer Reversal',
#     #     'content': '/CreditTransferReversalOFI'},
#     # {'title': 'Credit Transfer Proxy', 'content': '/CreditTransferProxyOFI'},
#     # {'title': 'Payment Status', 'content': '/PaymentStatusOFI'},
#     # {'title': 'Proxy Registration', 'content': '/ProxyRegistrationOFI'},
#     # {'title': 'Proxy Porting', 'content': '/ProxyPortingOFI'},
#     # {'title': 'Proxy Lookup', 'content': '/ProxyLookupOFI'},
#     # {'title': 'Proxy Enquiry', 'content': '/ProxyEnquiryOFI'},
#     # {'title': 'Proxy Deactivate', 'content': '/ProxyDeactivateOFI'},
#     # {'title': 'Request For Pay ByAccount',
#     #     'content': '/RequestForPayByAccountOFI'},
#     # {'title': 'Request For Pay ByProxy', 'content': '/RequestForPayByProxyOFI'},
#     # {'title': 'Request For Pay RejectByAccount',
#     #     'content': '/RequestForPayRejectByAccountOFI'},
#     # {'title': 'Request For Pay RejectByProxy',
#     #     'content': '/RequestForPayRejectByProxyOFI'},
#     # {'title': 'Credit Transfer RFP', 'content': '/CreditTransferRFPOFI'},
#     # {'title': 'Mandate Regist By Credit',
#     #     'content': '/MandateRegistByCreditOFI'},
#     # {'title': 'Mandate Regist By Debit', 'content': '/MandateRegistByDebitOFI'},
#     # {'title': 'Mandate Approval By Credit',
#     #     'content': '/MandateApprovalByCreditOFI'},
#     # {'title': 'Mandate Approval By Debit',
#     #     'content': '/MandateApprovalByDebitOFI'},
#     # {'title': 'Mandate Amend By Credit', 'content': '/MandateAmendByCreditOFI'},
#     # {'title': 'Mandate Amend By Debit', 'content': '/MandateAmendByDebitOFI'},
#     # {'title': 'Mandate Amend Approval By Credit',
#     #     'content': '/MandateAmendApprovalByCreditOFI'},
#     # {'title': 'Mandate Amend Approval By Debit',
#     #     'content': '/MandateAmendApprovalByDebitOFI'},
#     # {'title': 'Mandate Terminate By Credit',
#     #     'content': '/MandateTerminateByCreditOFI'},
#     # {'title': 'Mandate Terminate By Debit',
#     #     'content': '/MandateTerminateByDebitOFI'},
#     # {'title': 'Mandate Amend By Credit', 'content': '/MandateAmendByCreditOFI'},
#     # {'title': 'Mandate Enquiry', 'content': '/MandateEnquiry'},
#     # {'title': 'Direct Debit', 'content': '/DirectDebitOFI'},
#     # {'title': 'Payment Status DD', 'content': '/PaymentStatusDDOFI'},
# ]
